/*
 * GlyphSpek Trust Panel prototype (W1-19 / W1-27).
 *
 * Vanilla JS, zero dependencies, no build step. Open index.html directly.
 *
 * LOAD-BEARING PRINCIPLE
 * ----------------------
 * The agent's CLAIMS (what the actor says it did) and the independent
 * VERIFIER's VERDICT (an authoritative, signed VerifierVerdict) are NEVER
 * conflated. They render as visually distinct sections with distinct labels,
 * colors, and framing. An actor's self-reported success is not a verdict.
 *
 * Data shapes mirror spikes/p0-contracts:
 *   - TraceEvent envelope: { v, runId, seq, ts, type, prevHash, hash, payload }
 *   - TraceEventType: run_created | run_state_changed | policy_decision |
 *       tool_start | tool_end | redaction | prompt | model_call | verifier_verdict
 *   - PolicyDecision (7): allow | deny | ask | force_ask |
 *       allow_with_redaction | sandbox_only | read_only
 *   - VerifierVerdict: { checks[{name,command,status}], overallVerdict,
 *       traceRootHash, signature{alg,value,keyId} }
 *
 * SIGNATURE BEFORE DISPLAY (charter requirement)
 * ----------------------------------------------
 * The verifier verdict is shown as AUTHORITATIVE only after its Ed25519
 * detached signature is VERIFIED in-browser with Web Crypto. The scheme is
 * reproduced byte-for-byte from spikes/p0-contracts/SIGNING.md and
 * spikes/p0-verifier/signing.ts: the signed message is the UTF-8 bytes of
 *   canonicalJson({ traceRootHash, verdict-without-signature })
 * and the signature (base64) is checked against the verifier's SPKI public
 * key, resolved out-of-band (loaded with the bundle, NOT trusted from the
 * actor). If verification fails — or the browser lacks Web Crypto Ed25519
 * support — the verdict is shown as UNTRUSTED, never silently "verified".
 *
 * The DEFAULT sample (sample-bundle.js, generated by tools/generate-sample.mjs)
 * carries a REAL signature and verifies on open. Trace-chain hashes are
 * realistic-looking hex PLACEHOLDERS, not real chain hashes; the SIGNATURE is
 * real.
 */

'use strict';

/* ------------------------------------------------------------------ *
 * Embedded SAMPLE trace.
 *
 * Browsers block file:// fetch of a local .jsonl, so a representative
 * governed run is embedded. The DEFAULT sample is the REAL self-signed bundle
 * in sample-bundle.js (window.GLYPHSPEK_SAMPLE_BUNDLE); the MOCK below is kept
 * as a fallback (e.g. if sample-bundle.js is absent) and to show an unsigned
 * verdict for comparison. A real run bundle can be loaded via the file picker /
 * drag-drop.
 * ------------------------------------------------------------------ */

const SAMPLE_RUN_ID = '7f3c1a9e-4d22-4b8a-9c61-2e8f0a1b3c4d';

const SAMPLE_TRACE = [
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 0,
    ts: 1748539200000,
    type: 'run_created',
    prevHash: '',
    hash: 'a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff00',
    payload: {
      runId: SAMPLE_RUN_ID,
      runDir: '.glyphspek/runs/7f3c1a9e',
      provenanceLabel: 'user',
    },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 1,
    ts: 1748539200800,
    type: 'run_state_changed',
    prevHash: 'a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff00',
    hash: 'b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff0011',
    payload: { from: 'created', to: 'worktree_ready', reason: 'git worktree checked out' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 2,
    ts: 1748539201500,
    type: 'run_state_changed',
    prevHash: 'b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff0011',
    hash: 'c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff001122',
    payload: { from: 'worktree_ready', to: 'sandbox_ready', reason: 'sandbox namespace ready, egress default-deny' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 3,
    ts: 1748539202100,
    type: 'run_state_changed',
    prevHash: 'c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff001122',
    hash: 'd4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff00112233',
    payload: { from: 'sandbox_ready', to: 'executing', reason: 'actor loop started' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 4,
    ts: 1748539203000,
    type: 'model_call',
    prevHash: 'd4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff00112233',
    hash: 'e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff0011223344',
    payload: { model: 'claude-sonnet-4.6', inputTokens: 4120, outputTokens: 318, provenanceLabel: 'user' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 5,
    ts: 1748539204200,
    type: 'policy_decision',
    prevHash: 'e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff0011223344',
    hash: 'f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff001122334455',
    payload: {
      tool: 'command',
      requestedCapability: 'command:npm',
      decision: 'allow',
      provenanceLabel: 'repo',
      rule: 'allow.commands: ["npm","test"]',
    },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 6,
    ts: 1748539204300,
    type: 'tool_start',
    prevHash: 'f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff001122334455',
    hash: '0718293a4b5c6d7e8f90112233445566778899aabbccddeeff00112233445566',
    payload: { tool: 'command', requestedCapability: 'command:npm', argv: ['npm', 'test'], provenanceLabel: 'repo' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 7,
    ts: 1748539212600,
    type: 'tool_end',
    prevHash: '0718293a4b5c6d7e8f90112233445566778899aabbccddeeff00112233445566',
    hash: '18293a4b5c6d7e8f90112233445566778899aabbccddeeff0011223344556677',
    payload: { tool: 'command', requestedCapability: 'command:npm', argv: ['npm', 'test'], exitCode: 0, durationMs: 8300, provenanceLabel: 'tool-output' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 8,
    ts: 1748539213400,
    type: 'policy_decision',
    prevHash: '18293a4b5c6d7e8f90112233445566778899aabbccddeeff0011223344556677',
    hash: '293a4b5c6d7e8f90112233445566778899aabbccddeeff001122334455667788',
    payload: {
      tool: 'network',
      requestedCapability: 'network:registry.npmjs.org',
      decision: 'allow',
      provenanceLabel: 'repo',
      rule: 'allow.network: ["registry.npmjs.org"]',
      destination: 'https://registry.npmjs.org',
    },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 9,
    ts: 1748539214000,
    type: 'policy_decision',
    prevHash: '293a4b5c6d7e8f90112233445566778899aabbccddeeff001122334455667788',
    hash: '3a4b5c6d7e8f90112233445566778899aabbccddeeff00112233445566778899',
    payload: {
      tool: 'file_read',
      requestedCapability: 'file_read:.env',
      decision: 'ask',
      blocked: true,
      provenanceLabel: 'tool-output',
      rule: 'deny.read_paths: ["**/.env"] -> escalated to operator',
      argv: ['cat', '.env'],
    },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 10,
    ts: 1748539214100,
    type: 'redaction',
    prevHash: '3a4b5c6d7e8f90112233445566778899aabbccddeeff00112233445566778899',
    hash: '4b5c6d7e8f90112233445566778899aabbccddeeff0011223344556677889900',
    payload: {
      location: 'tool_end.output',
      reason: 'matched aws_secret_access_key pattern',
      field: 'AWS_SECRET_ACCESS_KEY',
    },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 11,
    ts: 1748539215800,
    type: 'run_state_changed',
    prevHash: '4b5c6d7e8f90112233445566778899aabbccddeeff0011223344556677889900',
    hash: '5c6d7e8f90112233445566778899aabbccddeeff001122334455667788990011',
    payload: { from: 'executing', to: 'completed', reason: 'actor reported task complete' },
  },
  {
    v: 1,
    runId: SAMPLE_RUN_ID,
    seq: 12,
    ts: 1748539216500,
    type: 'verifier_verdict',
    prevHash: '5c6d7e8f90112233445566778899aabbccddeeff001122334455667788990011',
    hash: '6d7e8f90112233445566778899aabbccddeeff00112233445566778899001122',
    payload: {
      checks: [
        { name: 'unit tests', command: ['npm', 'test'], status: 'pass' },
        { name: 'typecheck', command: ['npm', 'run', 'typecheck'], status: 'fail' },
      ],
      overallVerdict: 'fail',
      traceRootHash: '6d7e8f90112233445566778899aabbccddeeff00112233445566778899001122',
      // NON-VERIFYING placeholder signature (the MOCK sample). It will render as
      // "signature NOT verified" — demonstrating the gate. The DEFAULT sample
      // (sample-bundle.js) carries a REAL signature that verifies.
      signature: {
        alg: 'ed25519',
        value: 'k3JmZ0xQv7Yc2pN8wRtUaB4dE6fG1hI9jK0lM2nO3pQ4rS5tU6vW7xY8zA9bC0dEfGh==',
        keyId: 'verifier-trust-domain/2026-key-01',
      },
    },
  },
];

/*
 * The agent's CLAIMS — separate, actor-produced, NON-authoritative.
 * In a real run this would come from the actor's self-report (e.g. a
 * structured "summary" message), NOT from the verifier. Kept deliberately
 * apart from any VerifierVerdict so the two can never be substituted.
 */
const SAMPLE_ACTOR_CLAIMS = {
  plan: 'Fix the failing date-parsing helper and add a regression test.',
  summary:
    'Updated src/date.ts to handle ISO week dates and added a unit test. ' +
    'All tests pass and the change is ready to merge.',
  claimedChangedFiles: ['src/date.ts', 'test/date.test.ts'],
  claimedChecks: [
    { name: 'unit tests', claim: 'pass' },
    { name: 'typecheck', claim: 'pass' },
  ],
};

/* ------------------------------------------------------------------ *
 * Small DOM + formatting helpers (no framework).
 * ------------------------------------------------------------------ */

function el(tag, opts) {
  const node = document.createElement(tag);
  if (!opts) return node;
  if (opts.className) node.className = opts.className;
  if (opts.text != null) node.textContent = String(opts.text);
  if (opts.title) node.title = opts.title;
  if (opts.html != null) node.innerHTML = opts.html; // only used with trusted, escaped content
  return node;
}

function clear(node) {
  while (node.firstChild) node.removeChild(node.firstChild);
}

function fmtTime(ts) {
  if (typeof ts !== 'number') return String(ts);
  const d = new Date(ts);
  if (Number.isNaN(d.getTime())) return String(ts);
  return d.toISOString().replace('T', ' ').replace('Z', 'Z');
}

function shortHash(h) {
  if (typeof h !== 'string' || h.length === 0) return '(none)';
  if (h.length <= 16) return h;
  return h.slice(0, 10) + '…' + h.slice(-6);
}

function argvToString(argv) {
  if (!Array.isArray(argv)) return '';
  return argv.join(' ');
}

/* ================================================================== *
 * SIGNATURE VERIFICATION (signature-before-display gate).
 *
 * Reproduces the spikes signing scheme EXACTLY so the browser verify is
 * byte-for-byte identical to what the verifier signed:
 *
 *   message = UTF-8 bytes of canonicalJson({
 *               traceRootHash: <verdict.traceRootHash>,
 *               verdict: <verdict WITHOUT its `signature` field>
 *             })
 *
 * Sources: spikes/p0-contracts/SIGNING.md, spikes/p0-verifier/signing.ts,
 * spikes/p0-trace/canonical-json.ts.
 * ================================================================== */

/* ================================================================== *
 * PINNED TRUST ROOT (out-of-band verifier key set).
 *
 * SECURITY FIX (sweep-05 Critical): the panel previously verified the verdict
 * signature against state.verifierPublicKey, which is populated FROM THE BUNDLE
 * (loadBundle: bundle.verifierPublicKey). That let an attacker mint a key, sign
 * a passing verdict, embed the matching public key, and be marked AUTHORITATIVE.
 *
 * A verdict is AUTHORITATIVE only if its signature verifies against a key that
 * was provisioned OUT-OF-BAND — never a key carried by the bundle. The trusted
 * set below is the trust ROOT. The bundle-supplied key is retained ONLY to
 * detect the "signed by an untrusted (bundle) key" state for honest reporting;
 * it can NEVER make a verdict authoritative.
 * ================================================================== */

/*
 * DEMO-ONLY verifier public key. NOT A PRODUCT TRUST ROOT.
 *
 * This is the SPKI public key of the checked-in demo keypair
 * (prototypes/trust-panel/keys/demo-verifier-*.pem). It is pinned here so the
 * committed sample-bundle.js — signed by the matching demo PRIVATE key — opens
 * DEMO-AUTHORITATIVE (verified against this built-in DEMO trust root) without any
 * external key. This is NOT product AUTHORITATIVE: this demo key is NOT a product
 * trust root, and full product AUTHORITATIVE requires an out-of-band
 * product/operator key. It exists solely to demonstrate the trust gate. SHIPPING
 * A REAL PRODUCT MUST NOT RELY ON THIS KEY; real trust roots arrive via the
 * out-of-band seam below.
 */
const DEMO_VERIFIER_PUBLIC_KEY_PEM =
  '-----BEGIN PUBLIC KEY-----\n' +
  'MCowBQYDK2VwAyEAkkkfoonFJ16wuevqYQ3Vg0EVMyuMwYKgtojc9AsHgW0=\n' +
  '-----END PUBLIC KEY-----\n';

/**
 * TWO-TIER TRUST MODEL (sweep-06 High fix).
 *
 * The committed demo key MUST NOT confer PRODUCT authority — anyone with repo
 * access holds the matching demo PRIVATE key (prototypes/trust-panel/keys/
 * demo-verifier-private.pem) and could otherwise sign a fully-AUTHORITATIVE
 * bundle. So trust is split into two cryptographically-distinct tiers:
 *
 *   PRODUCT tier — keys provisioned OUT-OF-BAND ONLY, via the host:
 *     window.GLYPHSPEK_TRUSTED_VERIFIER_KEYS = ['<PEM or base64 SPKI>', ...]
 *     (in the VS Code extension this is the `glyphspek.trustedVerifierKeys`
 *     setting / operator keystore). A PRODUCT-tier match is the ONLY thing that
 *     can make a verdict FULLY AUTHORITATIVE. The built-in demo key is NOT here.
 *
 *   DEMO tier — the built-in DEMO_VERIFIER_PUBLIC_KEY_PEM ONLY. A DEMO-tier
 *     match yields the separate, clearly-labeled DEMO-AUTHORITATIVE state so the
 *     committed sample still demonstrates the gate, but it can NEVER be presented
 *     as production AUTHORITATIVE.
 *
 * A bundle's embedded verifierPublicKey is intentionally in NEITHER tier; it is
 * consulted last, only to label the "untrusted-key" state for honest reporting.
 */

/** The built-in DEMO tier: the committed demo key, and nothing else. */
const DEMO_VERIFIER_KEYS = [DEMO_VERIFIER_PUBLIC_KEY_PEM];

/**
 * Out-of-band seam: classify trusted keys into the two tiers. Reads the global
 * the embedder may define BEFORE app.js loads:
 *   window.GLYPHSPEK_TRUSTED_VERIFIER_KEYS = ['<PEM or base64 SPKI>', ...]
 * Those injected keys are PRODUCT tier. The built-in demo key is DEMO tier and
 * is NEVER silently folded into the product set. NEVER reads the bundle.
 *
 * Returns { productKeys, demoKeys } — each a de-duped array of key texts. A key
 * is de-duped by normalized DER id; if the SAME key is both injected (product)
 * and the built-in demo key, PRODUCT wins (it is removed from demoKeys) so an
 * operator who deliberately provisions that key out-of-band gets product trust,
 * while the built-in copy alone stays demo-only.
 *
 * Uses function declarations (publicKeyToDer / bytesToHex below) that are
 * hoisted, so the forward reference is safe at call time.
 */
function getTrustedVerifierKeys() {
  const injected =
    (typeof window !== 'undefined' && Array.isArray(window.GLYPHSPEK_TRUSTED_VERIFIER_KEYS))
      ? window.GLYPHSPEK_TRUSTED_VERIFIER_KEYS
      : [];

  // De-dupe each tier by normalized DER id. Malformed entries are skipped, not
  // fatal. `productIds` lets us keep a product key out of the demo tier.
  const productIds = new Set();
  const productKeys = [];
  for (const k of injected) {
    if (typeof k !== 'string' || !k.trim()) continue;
    let id;
    try { id = keyDerId(k); } catch (_) { continue; }
    if (productIds.has(id)) continue;
    productIds.add(id);
    productKeys.push(k);
  }

  const demoIds = new Set();
  const demoKeys = [];
  for (const k of DEMO_VERIFIER_KEYS) {
    if (typeof k !== 'string' || !k.trim()) continue;
    let id;
    try { id = keyDerId(k); } catch (_) { continue; }
    if (productIds.has(id) || demoIds.has(id)) continue; // product wins
    demoIds.add(id);
    demoKeys.push(k);
  }

  return { productKeys, demoKeys };
}

/** Normalize a key's SPKI body to a stable id (hex of DER) for de-dupe. */
function keyDerId(keyText) {
  // publicKeyToDer / bytesToHex are declared below; this helper is only called
  // after parse, by which point both hoisted declarations are bound.
  return bytesToHex(publicKeyToDer(keyText));
}

/**
 * Canonical JSON with stable (lexicographically sorted) keys at every level,
 * compact, UTF-8. Direct port of spikes/p0-trace/canonical-json.ts — it MUST
 * match byte-for-byte or signatures will not verify.
 */
function canonicalJson(obj) {
  return canonicalEncode(obj);
}

function canonicalEncode(value) {
  if (value === null) return 'null';
  const t = typeof value;
  if (t === 'string') return JSON.stringify(value);
  if (t === 'number') return Number.isFinite(value) ? String(value) : 'null';
  if (t === 'boolean') return value ? 'true' : 'false';
  if (Array.isArray(value)) {
    const parts = value.map((item) => (item === undefined ? 'null' : canonicalEncode(item)));
    return '[' + parts.join(',') + ']';
  }
  if (t === 'object') {
    const keys = Object.keys(value).sort();
    const parts = [];
    for (const key of keys) {
      const v = value[key];
      if (v === undefined) continue; // omit undefined, matching JSON.stringify
      parts.push(JSON.stringify(key) + ':' + canonicalEncode(v));
    }
    return '{' + parts.join(',') + '}';
  }
  if (t === 'bigint') throw new TypeError('Do not know how to serialize a BigInt');
  return 'undefined';
}

/**
 * Build the exact canonical message bytes that were signed: strip the verdict's
 * own `signature` field, then canonicalize { traceRootHash, verdict }.
 */
function verdictMessageBytes(verdict) {
  const core = {};
  for (const k of Object.keys(verdict)) {
    if (k === 'signature') continue;
    core[k] = verdict[k];
  }
  const json = canonicalJson({ traceRootHash: core.traceRootHash, verdict: core });
  return new TextEncoder().encode(json);
}

/** Decode a base64 string to a Uint8Array. Throws on malformed input. */
function base64ToBytes(b64) {
  const clean = String(b64).replace(/\s+/g, '');
  const bin = atob(clean); // throws on invalid base64
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/**
 * Normalize a verifier public key supplied as SPKI PEM or bare base64 SPKI to
 * DER bytes (Uint8Array) for crypto.subtle.importKey('spki', ...).
 */
function publicKeyToDer(keyText) {
  const text = String(keyText).trim();
  const body = text
    .replace(/-----BEGIN [^-]+-----/g, '')
    .replace(/-----END [^-]+-----/g, '')
    .replace(/\s+/g, '');
  return base64ToBytes(body);
}

/** True iff this environment exposes Web Crypto subtle (needed for verify). */
function hasWebCryptoSubtle() {
  return typeof crypto !== 'undefined' && crypto && typeof crypto.subtle !== 'undefined';
}

/**
 * Verify a VerifierVerdict's Ed25519 signature. Tries the TRUSTED (out-of-band)
 * key set FIRST; only a trusted-key match can make a verdict authoritative.
 * Keys are tried by TIER (see getTrustedVerifierKeys): PRODUCT first, then DEMO,
 * then — only to label the untrusted state — the BUNDLE-supplied key.
 *
 * Returns (never throws):
 *   { status, detail, trusted, tier }
 * where status ∈ 'verified' | 'failed' | 'no-signature' | 'no-key'
 *               | 'unsupported' | 'error'
 *   tier ∈ 'product'        -> verified by an out-of-band PRODUCT key (FULL auth)
 *        | 'demo'           -> verified by the built-in DEMO key (DEMO-AUTH only)
 *        | 'untrusted-key'  -> verified only by the BUNDLE-supplied key
 *        | null             -> no valid signature
 *   trusted: true  -> tier is 'product' OR 'demo' (a pinned trust root matched);
 *                     the GATE still branches on tier — only 'product' is FULLY
 *                     authoritative, 'demo' is DEMO-AUTHORITATIVE.
 *   trusted: false -> only the BUNDLE key verified it, or nothing did.
 * status==='verified' && tier==='product' is the ONLY full-authoritative case.
 */
async function verifyVerdictSignature(verdict, bundlePublicKeyText) {
  const sig = verdict && verdict.signature;
  if (!sig || typeof sig.value !== 'string') {
    return { status: 'no-signature', detail: 'verdict carries no signature', trusted: false, tier: null };
  }
  if (sig.alg !== 'ed25519') {
    return { status: 'failed', detail: 'unsupported signature alg: ' + sig.alg, trusted: false, tier: null };
  }
  if (!hasWebCryptoSubtle()) {
    return { status: 'unsupported', detail: 'Web Crypto (crypto.subtle) unavailable', trusted: false, tier: null };
  }

  let sigBytes;
  try { sigBytes = base64ToBytes(sig.value); }
  catch (err) { return { status: 'error', detail: 'malformed signature: ' + err.message, trusted: false, tier: null }; }

  const msg = verdictMessageBytes(verdict);

  const { productKeys, demoKeys } = getTrustedVerifierKeys();

  // (A) PRODUCT tier first. Any one that verifies => FULLY authoritative-eligible.
  for (const keyText of productKeys) {
    const ok = await verifyWithKey(keyText, sigBytes, msg);
    if (ok === 'unsupported') {
      return { status: 'unsupported', detail: 'this browser lacks Web Crypto Ed25519 support', trusted: false, tier: null };
    }
    if (ok === true) {
      return { status: 'verified', detail: 'Ed25519 signature valid for a TRUSTED (out-of-band) PRODUCT verifier key', trusted: true, tier: 'product' };
    }
  }

  // (B) DEMO tier next. A pass here is the built-in demo trust root only — it can
  //     reach DEMO-AUTHORITATIVE but is NEVER full product authoritative.
  for (const keyText of demoKeys) {
    const ok = await verifyWithKey(keyText, sigBytes, msg);
    if (ok === 'unsupported') {
      return { status: 'unsupported', detail: 'this browser lacks Web Crypto Ed25519 support', trusted: false, tier: null };
    }
    if (ok === true) {
      return { status: 'verified', detail: 'Ed25519 signature valid for the built-in DEMO verifier key — NOT a production trust root', trusted: true, tier: 'demo' };
    }
  }

  // (C) Bundle-supplied key, ONLY to label "valid but untrusted". A pass here is
  //     NOT authoritative — the key came from the (untrusted) bundle.
  if (bundlePublicKeyText) {
    const ok = await verifyWithKey(bundlePublicKeyText, sigBytes, msg);
    if (ok === true) {
      return {
        status: 'verified',
        detail: 'signature valid, but only for a key SUPPLIED BY THE BUNDLE — not a trusted out-of-band key',
        trusted: false,
        tier: 'untrusted-key',
      };
    }
  }

  if (productKeys.length === 0 && demoKeys.length === 0 && !bundlePublicKeyText) {
    return { status: 'no-key', detail: 'no trusted verifier key available', trusted: false, tier: null };
  }
  return { status: 'failed', detail: 'signature does NOT verify against any trusted or bundle key', trusted: false, tier: null };
}

/** Import one SPKI key and verify; returns true|false|'unsupported'. Never throws. */
async function verifyWithKey(keyText, sigBytes, msg) {
  let der, key;
  try { der = publicKeyToDer(keyText); }
  catch (_) { return false; }
  try {
    key = await crypto.subtle.importKey('spki', der, { name: 'Ed25519' }, false, ['verify']);
  } catch (_) {
    return 'unsupported';
  }
  try {
    return await crypto.subtle.verify({ name: 'Ed25519' }, key, sigBytes, msg);
  } catch (_) {
    return false;
  }
}

/* ================================================================== *
 * TRACE-CHAIN VERIFICATION (evidence-bundle integrity gate).
 *
 * A valid signature only proves the verdict OBJECT is authentic. It does NOT
 * prove the loaded trace is the one the verdict committed to. So before
 * presenting a verdict as AUTHORITATIVE we ALSO verify, in-browser:
 *   1. verifyChainBrowser(events).ok            — the hash chain is intact, and
 *   2. computeTraceRootBrowser(events) === verdict.traceRootHash — the loaded
 *      trace is exactly the one the verdict signed over.
 *
 * The hashing is reproduced BYTE-FOR-BYTE from spikes/p0-trace/trace-store.ts:
 *
 *   hash_n = sha256( prevHash_n + canonicalJson({v,runId,seq,ts,type,payload[,source]}) )
 *
 * — genesis prevHash is 64 hex zeros; `source` is folded into the hashed
 * content ONLY when present (source-less events hash exactly as before that
 * field existed); the trace root is simply the hash of the LAST event (GENESIS
 * for an empty trace), since each hash already commits to all prior history.
 * canonicalJson above is the same byte-exact port the signature path uses.
 * ================================================================== */

/** Genesis prevHash for the first event in a chain: 64 hex zeros. */
const GENESIS_HASH = '0'.repeat(64);

/**
 * The canonical content over which an event's hash is computed. EXCLUDES the
 * derived chain fields (prevHash, hash). `source` is included ONLY when present,
 * matching spikes/p0-trace/trace-store.ts hashableContent() exactly.
 */
function hashableContent(evt) {
  const content = {
    v: evt.v,
    runId: evt.runId,
    seq: evt.seq,
    ts: evt.ts,
    type: evt.type,
    payload: evt.payload,
  };
  if (evt.source !== undefined) content.source = evt.source;
  return content;
}

/** Hex-encode a buffer/Uint8Array as lowercase hex. */
function bytesToHex(buf) {
  const bytes = new Uint8Array(buf);
  let out = '';
  for (let i = 0; i < bytes.length; i++) {
    out += bytes[i].toString(16).padStart(2, '0');
  }
  return out;
}

/** sha256(prevHash + canonicalJson(content)) as lowercase hex (async, Web Crypto). */
async function computeEventHash(prevHash, evt) {
  const msg = new TextEncoder().encode(prevHash + canonicalJson(hashableContent(evt)));
  const digest = await crypto.subtle.digest('SHA-256', msg);
  return bytesToHex(digest);
}

/**
 * Recompute every event's hash and verify linkage, mirroring
 * spikes/p0-trace/trace-store.ts verifyChain(). Returns { ok, brokenIndex }.
 * For each event i: expected prevHash is GENESIS_HASH for i===0 else
 * events[i-1].hash, and the recomputed hash must equal the stored hash.
 * Returns { ok:false } with no brokenIndex if Web Crypto is unavailable.
 */
async function verifyChainBrowser(events) {
  if (!hasWebCryptoSubtle()) return { ok: false };
  const list = Array.isArray(events) ? events : [];
  let expectedPrev = GENESIS_HASH;
  for (let i = 0; i < list.length; i++) {
    const evt = list[i];
    if (evt.prevHash !== expectedPrev) return { ok: false, brokenIndex: i };
    const recomputed = await computeEventHash(evt.prevHash, evt);
    if (recomputed !== evt.hash) return { ok: false, brokenIndex: i };
    expectedPrev = evt.hash;
  }
  return { ok: true };
}

/**
 * Compute the trace root over an ordered event list: the hash of the LAST
 * event, or GENESIS_HASH for an empty trace. Mirrors computeTraceRoot() in
 * spikes/p0-trace/trace-store.ts. (Returns the stored last-event hash; pair
 * with verifyChainBrowser to confirm that stored hash is itself authentic.)
 */
function computeTraceRootBrowser(events) {
  const list = Array.isArray(events) ? events : [];
  if (list.length === 0) return GENESIS_HASH;
  return list[list.length - 1].hash;
}

/* ------------------------------------------------------------------ *
 * Application state.
 * ------------------------------------------------------------------ */

// Default to the REAL self-signed bundle (sample-bundle.js) when present, so the
// panel demonstrates ACTUAL in-browser verification on open. Fall back to the
// embedded MOCK trace (whose placeholder signature will NOT verify) otherwise.
const REAL_SAMPLE_BUNDLE =
  typeof window !== 'undefined' ? window.GLYPHSPEK_SAMPLE_BUNDLE : undefined;

const state = {
  trace: REAL_SAMPLE_BUNDLE ? REAL_SAMPLE_BUNDLE.events : SAMPLE_TRACE,
  claims: REAL_SAMPLE_BUNDLE ? REAL_SAMPLE_BUNDLE.claims || null : SAMPLE_ACTOR_CLAIMS,
  verifierPublicKey: REAL_SAMPLE_BUNDLE ? REAL_SAMPLE_BUNDLE.verifierPublicKey || null : null,
  source: REAL_SAMPLE_BUNDLE ? 'embedded signed sample' : 'embedded mock sample (no signature)',
  // A standalone verdict.json (capstone-style bundle), if loaded separately from
  // the trace. Takes precedence over an embedded verifier_verdict event. The
  // DEFAULT embedded sample carries its verdict DETACHED (REAL_SAMPLE_BUNDLE.verdict,
  // mirroring a real verdict.json) so the trace can end at the exact event the
  // verdict committed to — making computeTraceRoot(events) === verdict.traceRootHash
  // and the bundle DEMO-AUTHORITATIVE on open (pinned demo trust root, NOT a production verdict).
  standaloneVerdict: REAL_SAMPLE_BUNDLE ? REAL_SAMPLE_BUNDLE.verdict || null : null,
  // Latest async verification result for the current trace's verdict.
  sigResult: null,
  // Latest async trace-chain/root integrity result for the current trace.
  // { sigResult-aligned } shape: { chainOk, brokenIndex, recomputedRoot,
  // rootMatches } — null until computed. Used (with sigResult) to gate whether
  // the verdict is AUTHORITATIVE or merely signature-valid-but-inconsistent.
  chainResult: null,
};

/* ------------------------------------------------------------------ *
 * Derivations from the trace.
 * ------------------------------------------------------------------ */

function deriveRunHeader(trace) {
  const created = trace.find((e) => e.type === 'run_created');
  const runId = created ? (created.payload && created.payload.runId) || created.runId : trace[0] && trace[0].runId;
  const stateChanges = trace.filter((e) => e.type === 'run_state_changed');
  const last = stateChanges[stateChanges.length - 1];
  const status = last ? last.payload.to : created ? 'created' : 'unknown';
  const modelCall = trace.find((e) => e.type === 'model_call');
  const model = modelCall ? modelCall.payload.model : null;
  const tokens = trace
    .filter((e) => e.type === 'model_call')
    .reduce(
      (acc, e) => {
        acc.input += e.payload.inputTokens || 0;
        acc.output += e.payload.outputTokens || 0;
        return acc;
      },
      { input: 0, output: 0 },
    );
  const runDir = created && created.payload ? created.payload.runDir : null;
  return { runId, status, model, tokens, runDir };
}

function deriveVerdict(trace) {
  // A standalone verdict.json (e.g. the capstone bundle) takes precedence over
  // a verifier_verdict event embedded in the trace.
  if (state.standaloneVerdict) return state.standaloneVerdict;
  const evt = trace.find((e) => e.type === 'verifier_verdict');
  return evt ? evt.payload : null;
}

/** True if `obj` is a standalone VerifierVerdict (verdict.json), not a trace. */
function isVerdictObject(obj) {
  return (
    obj &&
    typeof obj === 'object' &&
    !Array.isArray(obj) &&
    Array.isArray(obj.checks) &&
    typeof obj.traceRootHash === 'string' &&
    !Array.isArray(obj.events)
  );
}

function deriveCommands(trace) {
  // A command "ran" if there is a tool_start/tool_end for it. We pair by argv.
  const out = [];
  for (const e of trace) {
    if (e.type === 'tool_end' && e.payload && e.payload.tool === 'command') {
      out.push({
        argv: e.payload.argv || [],
        exitCode: e.payload.exitCode,
        durationMs: e.payload.durationMs,
      });
    }
  }
  return out;
}

function deriveNetwork(trace) {
  const out = [];
  for (const e of trace) {
    if (e.type === 'policy_decision' && e.payload && e.payload.tool === 'network') {
      // F1: an observe-only egress is OBSERVED on the bypassable soft plane, NOT a
      // policy allow — surface it distinctly so it never reads as "policy: allowed".
      const obs = e.payload.enforcement === 'observe-only';
      out.push({
        destination: e.payload.destination || e.payload.requestedCapability,
        decision: e.payload.decision,
        blocked: obs ? false : !!e.payload.blocked,
        observeOnly: obs,
      });
    }
  }
  return out;
}

function derivePolicyDecisions(trace) {
  return trace
    .filter((e) => e.type === 'policy_decision')
    .map((e) => {
      const obs = e.payload.enforcement === 'observe-only';
      return {
        tool: e.payload.tool,
        requestedCapability: e.payload.requestedCapability,
        decision: e.payload.decision,
        blocked: obs ? false : !!e.payload.blocked,
        rule: e.payload.rule,
        provenanceLabel: e.payload.provenanceLabel,
        enforcement: obs ? 'observe-only' : undefined,
      };
    });
}

/* ------------------------------------------------------------------ *
 * Renderers.
 * ------------------------------------------------------------------ */

function renderRunHeader() {
  const h = deriveRunHeader(state.trace);
  const root = document.getElementById('run-header');
  clear(root);

  const idRow = el('div', { className: 'run-id-row' });
  idRow.appendChild(el('span', { className: 'run-id-label', text: 'Run' }));
  idRow.appendChild(el('code', { className: 'run-id', text: h.runId || '(unknown)' }));
  const statusBadge = el('span', { className: 'status-badge status-' + (h.status || 'unknown'), text: h.status || 'unknown' });
  idRow.appendChild(statusBadge);
  root.appendChild(idRow);

  const meta = el('div', { className: 'run-meta' });
  meta.appendChild(metaItem('Model', h.model || 'n/a (placeholder)'));
  const tokenText = h.tokens.input || h.tokens.output ? h.tokens.input + ' in / ' + h.tokens.output + ' out' : 'n/a';
  meta.appendChild(metaItem('Tokens', tokenText));
  meta.appendChild(metaItem('Est. cost', 'n/a (placeholder)'));
  meta.appendChild(metaItem('Run dir', h.runDir || 'n/a'));
  meta.appendChild(metaItem('Source', state.source));
  root.appendChild(meta);
}

function metaItem(label, value) {
  const item = el('div', { className: 'meta-item' });
  item.appendChild(el('span', { className: 'meta-label', text: label }));
  item.appendChild(el('span', { className: 'meta-value', text: value }));
  return item;
}

function renderTimeline() {
  const root = document.getElementById('timeline');
  clear(root);

  for (const evt of state.trace) {
    const row = el('div', { className: 'event event-' + evt.type });

    const gutter = el('div', { className: 'event-gutter' });
    gutter.appendChild(el('span', { className: 'event-seq', text: '#' + evt.seq }));
    gutter.appendChild(el('span', { className: 'event-time', text: fmtTime(evt.ts) }));
    row.appendChild(gutter);

    const body = el('div', { className: 'event-body' });

    const head = el('div', { className: 'event-head' });
    head.appendChild(el('span', { className: 'event-type type-' + evt.type, text: evt.type }));

    // Per-type flags / summary chips.
    const chips = el('span', { className: 'event-chips' });
    appendEventChips(chips, evt);
    head.appendChild(chips);
    body.appendChild(head);

    const detail = el('div', { className: 'event-detail' });
    detail.textContent = summarizePayload(evt);
    body.appendChild(detail);

    const hashLine = el('div', { className: 'event-hash', title: 'hash placeholder (not a real chain hash)' });
    hashLine.textContent = 'hash ' + shortHash(evt.hash) + '  ← prev ' + shortHash(evt.prevHash);
    body.appendChild(hashLine);

    row.appendChild(body);
    root.appendChild(row);
  }
}

function appendEventChips(container, evt) {
  const p = evt.payload || {};
  if (evt.type === 'policy_decision') {
    container.appendChild(el('span', { className: 'chip chip-decision decision-' + p.decision, text: p.decision }));
    if (p.requestedCapability) container.appendChild(el('span', { className: 'chip chip-cap', text: p.requestedCapability }));
    if (p.blocked) container.appendChild(el('span', { className: 'chip chip-blocked', text: 'BLOCKED — not executed' }));
  } else if (evt.type === 'tool_start') {
    container.appendChild(el('span', { className: 'chip chip-cap', text: p.requestedCapability || p.tool }));
  } else if (evt.type === 'tool_end') {
    const code = p.exitCode;
    const cls = code === 0 ? 'exit-ok' : 'exit-bad';
    container.appendChild(el('span', { className: 'chip chip-exit ' + cls, text: 'exit ' + (code == null ? '?' : code) }));
    if (typeof p.durationMs === 'number') container.appendChild(el('span', { className: 'chip chip-dim', text: p.durationMs + ' ms' }));
  } else if (evt.type === 'redaction') {
    container.appendChild(el('span', { className: 'chip chip-redaction', text: 'SECRET REDACTED' }));
    if (p.field) container.appendChild(el('span', { className: 'chip chip-dim', text: 'field: ' + p.field }));
  } else if (evt.type === 'run_state_changed') {
    container.appendChild(el('span', { className: 'chip chip-state', text: p.from + ' → ' + p.to }));
  } else if (evt.type === 'model_call') {
    container.appendChild(el('span', { className: 'chip chip-dim', text: p.model }));
  }
  if (p.provenanceLabel) {
    container.appendChild(el('span', { className: 'chip chip-prov prov-' + p.provenanceLabel, text: 'prov: ' + p.provenanceLabel }));
  }
}

function summarizePayload(evt) {
  const p = evt.payload || {};
  switch (evt.type) {
    case 'run_created':
      return 'runDir=' + (p.runDir || '?');
    case 'run_state_changed':
      return p.reason || '';
    case 'policy_decision':
      return [
        'tool=' + p.tool,
        p.argv ? 'cmd="' + argvToString(p.argv) + '"' : null,
        p.destination ? 'dest=' + p.destination : null,
        p.rule ? 'rule=' + p.rule : null,
      ]
        .filter(Boolean)
        .join('   ');
    case 'tool_start':
      return p.argv ? '$ ' + argvToString(p.argv) : 'tool=' + p.tool;
    case 'tool_end':
      return (p.argv ? '$ ' + argvToString(p.argv) : 'tool=' + p.tool) + '   exitCode=' + (p.exitCode == null ? '?' : p.exitCode);
    case 'redaction':
      // NEVER show the secret value. Only location/reason/field metadata.
      return 'location=' + p.location + '   reason=' + p.reason + '   field=' + p.field + '   (value never recorded)';
    case 'model_call':
      return 'model=' + p.model + '   tokens=' + (p.inputTokens || 0) + ' in / ' + (p.outputTokens || 0) + ' out';
    case 'prompt':
      return 'role=' + p.role + '   (content may be redacted)';
    case 'verifier_verdict':
      return 'overall=' + p.overallVerdict + '   checks=' + (p.checks ? p.checks.length : 0) + '   (see Verifier Verdict panel)';
    default:
      return JSON.stringify(p);
  }
}

function renderClaimsVsVerdict() {
  renderActorClaims();
  renderVerifierVerdict();
}

function renderActorClaims() {
  const root = document.getElementById('actor-claims-body');
  clear(root);
  const c = state.claims;

  if (!c) {
    root.appendChild(el('p', { className: 'empty', text: 'No actor claims in this trace.' }));
    return;
  }

  root.appendChild(fieldBlock('Plan', c.plan));
  root.appendChild(fieldBlock('Self-reported summary', c.summary));

  if (Array.isArray(c.claimedChangedFiles) && c.claimedChangedFiles.length) {
    const wrap = el('div', { className: 'field' });
    wrap.appendChild(el('div', { className: 'field-label', text: 'Claimed changed files' }));
    const ul = el('ul', { className: 'plain-list' });
    for (const f of c.claimedChangedFiles) ul.appendChild(el('li', { html: '<code>' + escapeHtml(f) + '</code>' }));
    wrap.appendChild(ul);
    root.appendChild(wrap);
  }

  if (Array.isArray(c.claimedChecks) && c.claimedChecks.length) {
    const wrap = el('div', { className: 'field' });
    wrap.appendChild(el('div', { className: 'field-label', text: 'Claimed check results (UNVERIFIED)' }));
    const tbl = el('table', { className: 'mini-table' });
    for (const ck of c.claimedChecks) {
      const tr = el('tr');
      tr.appendChild(el('td', { text: ck.name }));
      const td = el('td');
      td.appendChild(el('span', { className: 'claim-pill claim-' + ck.claim, text: 'claims: ' + ck.claim }));
      tr.appendChild(td);
      tbl.appendChild(tr);
    }
    wrap.appendChild(tbl);
    root.appendChild(wrap);
  }
}

function fieldBlock(label, value) {
  const wrap = el('div', { className: 'field' });
  wrap.appendChild(el('div', { className: 'field-label', text: label }));
  wrap.appendChild(el('div', { className: 'field-value', text: value || '(none)' }));
  return wrap;
}

function renderVerifierVerdict() {
  const root = document.getElementById('verifier-verdict-body');
  const card = document.getElementById('verifier-verdict-card');
  clear(root);
  const v = deriveVerdict(state.trace);

  if (!v) {
    if (card) card.classList.remove('verdict-untrusted');
    root.appendChild(el('p', { className: 'empty', text: 'No verifier verdict in this trace. The run is unverified.' }));
    return;
  }

  // GATE (additive, defense-in-depth). A verdict is AUTHORITATIVE only when ALL
  // of these hold:
  //   (1) the Ed25519 signature over the verdict object VERIFIES, AND
  //   (2) the loaded trace's hash chain is intact (verifyChainBrowser.ok), AND
  //   (3) the recomputed trace root === verdict.traceRootHash.
  // A valid signature with a broken chain OR a non-matching root means the
  // verdict is cryptographically authentic but is NOT bound to the trace shown
  // here — the EVIDENCE BUNDLE is untrusted/inconsistent, so we de-authoritate.
  const res = state.sigResult;
  const sigVerified = !!res && res.status === 'verified';          // any key verified
  const tier = sigVerified ? res.tier : null;                       // 'product'|'demo'|'untrusted-key'|null
  const sigVerifiedByProduct = sigVerified && tier === 'product';   // out-of-band PRODUCT key verified
  const sigVerifiedByDemo     = sigVerified && tier === 'demo';     // built-in DEMO key verified
  // A pinned trust root (product OR demo) matched — eligible for SOME verified
  // state; the gate below still distinguishes full vs demo authority by tier.
  const sigVerifiedByTrusted = sigVerifiedByProduct || sigVerifiedByDemo;
  const sigValidUntrustedKey  = sigVerified && tier === 'untrusted-key'; // only bundle key verified
  const chain = state.chainResult;
  // Treat the bundle integrity as satisfied only once the async chain check has
  // resolved AND both legs pass. While pending (chain === null) we are NOT yet
  // authoritative.
  const bundleConsistent = !!chain && chain.chainOk === true && chain.rootMatches === true;

  // FULL (PRODUCT) AUTHORITATIVE requires a PRODUCT-tier signature AND a
  // consistent bundle. The DEMO tier can NEVER reach this state.
  const verified = sigVerifiedByProduct && bundleConsistent;

  // DEMO-AUTHORITATIVE: a DEMO-tier signature AND a consistent bundle. A real,
  // honest "the demo works" state — verified against the built-in DEMO trust
  // root, but explicitly NOT a production verifier.
  const demoAuthoritative = sigVerifiedByDemo && bundleConsistent;

  // Signature valid (by a trusted product OR demo key) but the bundle doesn't
  // back it — the existing "inconsistent" mode. An untrusted-key signature is
  // already non-authoritative regardless of chain.
  const sigValidButInconsistent = sigVerifiedByTrusted && !!chain && !bundleConsistent;

  // De-authoritative styling on the whole panel when not FULLY authoritative.
  // The demo-authoritative state gets its own distinct (non-product) treatment.
  if (card) {
    card.classList.toggle('verdict-untrusted', !verified && !demoAuthoritative);
    card.classList.toggle('verdict-demo-authoritative', demoAuthoritative); // NEW
    card.classList.toggle('verdict-inconsistent', sigValidButInconsistent);
    card.classList.toggle('verdict-untrusted-key', sigValidUntrustedKey);
  }

  // Signature badge FIRST — it is the gate, so it leads. Pass the resolved tier
  // and full-authoritative boolean so the badge can show product vs demo vs
  // untrusted-key honestly, never collapsing demo into product authority.
  root.appendChild(buildSigBadge(v.signature, res, verified, demoAuthoritative));

  // Trace-binding badge SECOND — the evidence-bundle integrity gate. Only shown
  // once the signature verified BY A TRUSTED (product OR demo) KEY (otherwise the
  // signature badge already tells the whole story; we never show "evidence
  // bundle verified" for a signature produced by an untrusted bundle key).
  if (sigVerifiedByTrusted) {
    root.appendChild(buildChainBadge(chain, verified || demoAuthoritative));
  }

  // Overall verdict banner.
  if (verified) {
    const banner = el('div', { className: 'verdict-banner verdict-' + v.overallVerdict });
    banner.appendChild(el('span', { className: 'verdict-label', text: 'OVERALL VERDICT' }));
    banner.appendChild(el('span', { className: 'verdict-value', text: (v.overallVerdict || 'unknown').toUpperCase() }));
    root.appendChild(banner);
  } else if (demoAuthoritative) {
    // DEMO-AUTHORITATIVE: chain + root verified against the built-in DEMO trust
    // root. Honest "the demo works" state, but a clearly distinct, NON-product
    // banner — it MUST NOT be mistaken for full production AUTHORITATIVE.
    const banner = el('div', { className: 'verdict-banner verdict-demo-authoritative-banner' });
    banner.appendChild(el('span', { className: 'verdict-label', text: 'DEMO-AUTHORITATIVE' }));
    banner.appendChild(
      el('span', {
        className: 'verdict-value',
        text:
          'verified against the built-in DEMO trust root, NOT a production verifier — claims "' +
          (v.overallVerdict || 'unknown').toUpperCase() + '"',
      }),
    );
    root.appendChild(banner);
  } else if (sigValidButInconsistent) {
    // Signature is cryptographically valid (trusted key), but the bundle it
    // signed is not the trace shown here. Do NOT present pass/fail as proven.
    const banner = el('div', { className: 'verdict-banner verdict-inconsistent-banner' });
    banner.appendChild(el('span', { className: 'verdict-label', text: 'VERDICT — INCONSISTENT BUNDLE' }));
    banner.appendChild(
      el('span', {
        className: 'verdict-value',
        text: '(signature valid, but NOT bound to this trace)',
      }),
    );
    root.appendChild(banner);
  } else if (sigValidUntrustedKey) {                                       // NEW
    // Signature is cryptographically valid, but ONLY against a key supplied by
    // the (untrusted) bundle — never a pinned out-of-band verifier key.
    const banner = el('div', { className: 'verdict-banner verdict-untrusted-key-banner' });
    banner.appendChild(el('span', { className: 'verdict-label', text: 'VERDICT — UNTRUSTED KEY' }));
    banner.appendChild(
      el('span', {
        className: 'verdict-value',
        text: '(signature valid, but signed by an UNTRUSTED key supplied by the bundle)',
      }),
    );
    root.appendChild(banner);
  } else {
    const banner = el('div', { className: 'verdict-banner verdict-untrusted-banner' });
    banner.appendChild(el('span', { className: 'verdict-label', text: 'VERDICT — UNTRUSTED' }));
    banner.appendChild(
      el('span', {
        className: 'verdict-value',
        text: '(claims "' + (v.overallVerdict || 'unknown').toUpperCase() + '")',
      }),
    );
    root.appendChild(banner);
  }

  // Per-check results.
  const checksWrap = el('div', { className: 'field' });
  checksWrap.appendChild(el('div', { className: 'field-label', text: 'Checks (sourced from Policy.verify — actor cannot narrow)' }));
  const tbl = el('table', { className: 'mini-table check-table' });
  for (const ck of v.checks || []) {
    const tr = el('tr');
    tr.appendChild(el('td', { text: ck.name }));
    const cmdTd = el('td');
    cmdTd.appendChild(el('code', { text: argvToString(ck.command) }));
    tr.appendChild(cmdTd);
    const statTd = el('td');
    statTd.appendChild(el('span', { className: 'verdict-pill check-' + ck.status, text: ck.status }));
    tr.appendChild(statTd);
    tbl.appendChild(tr);
  }
  checksWrap.appendChild(tbl);
  root.appendChild(checksWrap);

  // Trace root hash binding.
  const rootHash = el('div', { className: 'field' });
  rootHash.appendChild(el('div', { className: 'field-label', text: 'Bound trace_root_hash' }));
  rootHash.appendChild(el('code', { className: 'field-value mono', text: v.traceRootHash || '(none)' }));
  root.appendChild(rootHash);
}

/**
 * Build the signature gate badge. `verified === true` is the ONLY state that
 * presents the verdict as full (PRODUCT) authoritative. `demoAuthoritative`
 * gets a clearly distinct DEMO badge — verified against the built-in demo trust
 * root, never presented as production authority. Every other state is shown as
 * de-authoritative and explicitly NOT verified (never silently "verified").
 */
function buildSigBadge(sig, res, verified, demoAuthoritative) {
  const status = res ? res.status : sig ? 'pending' : 'no-signature';
  const detail = res ? res.detail : '';

  // Signature cryptographically valid, but ONLY for a key SUPPLIED BY THE BUNDLE
  // (tier 'untrusted-key'). Honest, distinct from "no signature" and from a
  // genuine verify failure — its own caution badge, never authoritative.
  if (res && res.status === 'verified' && res.tier === 'untrusted-key') {
    const badge = el('div', { className: 'sig-badge sig-untrusted-key' });
    badge.appendChild(el('span', { className: 'sig-x', text: '⚠' }));
    const txt = el('span', {
      text: '⚠ signature NOT trusted — valid only for a key SUPPLIED BY THE BUNDLE, not a pinned out-of-band verifier key',
    });
    if (res.detail) txt.title = res.detail;
    badge.appendChild(txt);
    return badge;
  }

  // DEMO tier verified AND bundle-consistent: a real verified state, but against
  // the built-in DEMO trust root only. Distinct badge — NEVER the green product
  // "authoritative" badge.
  if (demoAuthoritative) {
    const badge = el('div', { className: 'sig-badge sig-demo-authoritative' });
    badge.appendChild(el('span', { className: 'sig-check', text: '✓' }));
    const txt = el('span');
    txt.appendChild(el('strong', { text: 'signature verified ✓ (DEMO trust root)' }));
    txt.appendChild(
      el('span', {
        text:
          ' — DEMO-AUTHORITATIVE. Ed25519, verified in-browser against the BUILT-IN DEMO verifier key, NOT a production trust root. Provision an out-of-band key (GLYPHSPEK_TRUSTED_VERIFIER_KEYS) for full authority.',
      }),
    );
    // keyId is DISPLAY-ONLY (never the basis of trust): shown as a title label.
    if (sig) txt.title = 'keyId (label only, not trusted): ' + sig.keyId + '\n' + sig.value;
    badge.appendChild(txt);
    return badge;
  }

  const badge = el('div', { className: 'sig-badge ' + (verified ? 'sig-present' : 'sig-failed') });

  if (verified) {
    badge.appendChild(el('span', { className: 'sig-check', text: '✓' }));
    const txt = el('span');
    txt.appendChild(el('strong', { text: 'signature verified ✓' }));
    txt.appendChild(
      el('span', {
        text:
          ' — authoritative. Ed25519, verified in-browser against a TRUSTED (out-of-band) PRODUCT verifier key over canonical (verdict, traceRootHash).',
      }),
    );
    // keyId is DISPLAY-ONLY (never the basis of trust): shown as a title label.
    if (sig) txt.title = 'keyId (label only, not trusted): ' + sig.keyId + '\n' + sig.value;
    badge.appendChild(txt);
    return badge;
  }

  // Not verified — choose an exact, honest message per failure mode.
  badge.appendChild(el('span', { className: 'sig-x', text: '⚠' }));
  let message;
  switch (status) {
    case 'pending':
      message = 'verifying signature…';
      break;
    case 'no-signature':
      message = '⚠ signature NOT verified — verdict shown as UNTRUSTED (no signature present)';
      break;
    case 'no-key':
      message =
        '⚠ signature NOT verified — verdict shown as UNTRUSTED (no verifier public key loaded with the bundle)';
      break;
    case 'unsupported':
      message =
        '⚠ signature NOT verified — verdict shown as UNTRUSTED (' +
        (detail || 'Web Crypto Ed25519 unsupported') +
        ')';
      break;
    case 'failed':
    case 'error':
    default:
      message = '⚠ signature NOT verified — verdict shown as UNTRUSTED';
      break;
  }
  const txt = el('span', { text: message });
  if (detail && status !== 'unsupported') txt.title = detail;
  badge.appendChild(txt);
  return badge;
}

/**
 * Build the trace-binding (evidence-bundle integrity) badge. Shown only after
 * the signature verified. `bundleConsistent === true` means the chain is intact
 * AND the recomputed root matches verdict.traceRootHash — only then is the
 * verdict authoritative. On a MISMATCH we show the recomputed-root vs
 * verdict-root so the inconsistency is visible (the finding's requirement).
 */
function buildChainBadge(chain, bundleConsistent) {
  // Pending: chain check has not resolved yet.
  if (!chain) {
    const badge = el('div', { className: 'sig-badge sig-failed' });
    badge.appendChild(el('span', { className: 'sig-x', text: '…' }));
    badge.appendChild(el('span', { text: 'verifying trace chain + root binding…' }));
    return badge;
  }

  if (bundleConsistent) {
    const badge = el('div', { className: 'sig-badge sig-present' });
    badge.appendChild(el('span', { className: 'sig-check', text: '✓' }));
    const txt = el('span');
    txt.appendChild(el('strong', { text: 'evidence bundle verified ✓' }));
    txt.appendChild(
      el('span', {
        text:
          ' — hash chain intact and trace root matches the signed verdict ' +
          '(' + shortHash(chain.recomputedRoot) + ').',
      }),
    );
    badge.appendChild(txt);
    return badge;
  }

  // Inconsistent: signature was valid but the bundle does not back it.
  const badge = el('div', { className: 'sig-badge sig-failed' });
  badge.appendChild(el('span', { className: 'sig-x', text: '⚠' }));
  const txt = el('span');
  if (!chain.chainOk) {
    txt.appendChild(el('strong', { text: '⚠ evidence bundle UNTRUSTED — trace chain BROKEN' }));
    const where =
      typeof chain.brokenIndex === 'number'
        ? ' (first broken at event #' + chain.brokenIndex + ')'
        : '';
    txt.appendChild(
      el('span', {
        text:
          where +
          '. The signature is cryptographically valid, but the loaded trace ' +
          'fails hash-chain verification, so the verdict is NOT bound to it.',
      }),
    );
  } else {
    txt.appendChild(el('strong', { text: '⚠ evidence bundle INCONSISTENT — trace root does NOT match verdict' }));
    txt.appendChild(
      el('span', {
        text:
          '. The signature is cryptographically valid over the verdict, but the ' +
          'loaded trace is not the one it committed to (root mismatch).',
      }),
    );
  }
  badge.appendChild(txt);

  // Always surface recomputed-root vs verdict-root on mismatch.
  const cmp = el('div', { className: 'chain-root-compare' });
  const reLine = el('div', { className: 'field' });
  reLine.appendChild(el('span', { className: 'meta-label', text: 'recomputed trace root: ' }));
  reLine.appendChild(el('code', { className: 'mono', text: chain.recomputedRoot || '(none)' }));
  const vdLine = el('div', { className: 'field' });
  vdLine.appendChild(el('span', { className: 'meta-label', text: 'verdict.traceRootHash: ' }));
  vdLine.appendChild(el('code', { className: 'mono', text: chain.verdictRoot || '(none)' }));
  cmp.appendChild(reLine);
  cmp.appendChild(vdLine);
  badge.appendChild(cmp);

  return badge;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderDerivedSections() {
  renderCommands();
  renderNetwork();
  renderPolicyDecisions();
}

function renderCommands() {
  const root = document.getElementById('commands-body');
  clear(root);
  const cmds = deriveCommands(state.trace);
  if (!cmds.length) {
    root.appendChild(el('p', { className: 'empty', text: 'No commands executed.' }));
    return;
  }
  const tbl = el('table', { className: 'mini-table' });
  for (const c of cmds) {
    const tr = el('tr');
    const td = el('td');
    td.appendChild(el('code', { text: '$ ' + argvToString(c.argv) }));
    tr.appendChild(td);
    const code = el('td');
    code.appendChild(el('span', { className: 'chip chip-exit ' + (c.exitCode === 0 ? 'exit-ok' : 'exit-bad'), text: 'exit ' + (c.exitCode == null ? '?' : c.exitCode) }));
    tr.appendChild(code);
    tbl.appendChild(tr);
  }
  root.appendChild(tbl);
}

function renderNetwork() {
  const root = document.getElementById('network-body');
  clear(root);
  const nets = deriveNetwork(state.trace);
  if (!nets.length) {
    root.appendChild(el('p', { className: 'empty', text: 'No network destinations.' }));
    return;
  }
  const tbl = el('table', { className: 'mini-table' });
  for (const n of nets) {
    const tr = el('tr');
    const td = el('td');
    td.appendChild(el('code', { text: n.destination }));
    tr.appendChild(td);
    const dec = el('td');
    // F1: observe-only egress reads as OBSERVED (soft default-allow), distinct from
    // a real "policy: allowed".
    if (n.observeOnly) {
      dec.appendChild(el('span', { className: 'chip chip-decision decision-observe', text: 'observed (soft, default-allow)' }));
    } else if (n.decision === 'allow') {
      dec.appendChild(el('span', { className: 'chip chip-decision decision-allow', text: 'policy: allowed' }));
    } else {
      dec.appendChild(el('span', { className: 'chip chip-decision decision-' + n.decision, text: n.decision }));
    }
    tr.appendChild(dec);
    tbl.appendChild(tr);
  }
  root.appendChild(tbl);
}

function renderPolicyDecisions() {
  const root = document.getElementById('policy-body');
  clear(root);
  const decisions = derivePolicyDecisions(state.trace);
  if (!decisions.length) {
    root.appendChild(el('p', { className: 'empty', text: 'No policy decisions.' }));
    return;
  }
  const tbl = el('table', { className: 'mini-table policy-table' });
  const head = el('tr', { className: 'mini-head' });
  ['capability', 'decision', 'provenance', 'rule'].forEach((h) => head.appendChild(el('th', { text: h })));
  tbl.appendChild(head);
  for (const d of decisions) {
    const tr = el('tr');
    const cap = el('td');
    cap.appendChild(el('code', { text: d.requestedCapability }));
    if (d.blocked) cap.appendChild(el('span', { className: 'chip chip-blocked', text: 'blocked' }));
    tr.appendChild(cap);
    const dec = el('td');
    // F1: a soft-plane observe-only decision is OBSERVED (bypassable default-allow),
    // NOT a real policy allow — label it distinctly, mirroring the Network table.
    if (d.enforcement === 'observe-only') {
      dec.appendChild(el('span', { className: 'chip chip-decision decision-observe', text: 'observed (soft, default-allow)' }));
    } else {
      dec.appendChild(el('span', { className: 'chip chip-decision decision-' + d.decision, text: d.decision }));
    }
    tr.appendChild(dec);
    tr.appendChild(el('td', { text: d.provenanceLabel || '—' }));
    const rule = el('td', { className: 'rule-cell' });
    rule.textContent = d.rule || '—';
    tr.appendChild(rule);
    tbl.appendChild(tr);
  }
  root.appendChild(tbl);
}

/* ------------------------------------------------------------------ *
 * Loading real traces + export.
 * ------------------------------------------------------------------ */

/**
 * Parse one .json / .jsonl text blob into { events, claims, verifierPublicKey }.
 * Accepts:
 *   - a JSON array of TraceEvent envelopes,
 *   - JSONL (one TraceEvent per line),
 *   - a single TraceEvent object,
 *   - a wrapper { events:[...], claims:{...}, verifierPublicKey:"<PEM|base64>" }.
 * `verifierPublicKey` / `claims` are optional; absent fields stay null so we
 * never silently borrow them from another source on a trust surface.
 */
function parseTraceText(text) {
  const trimmed = text.trim();
  if (!trimmed) throw new Error('empty file');
  let events = null;
  let claims = null;
  let verifierPublicKey = null;

  // JSONL detection FIRST: a real trace.jsonl (one TraceEvent per line) has
  // multiple lines each starting with `{`. We must not try to JSON.parse the
  // whole file as a single object in that case.
  const lines = trimmed.split('\n').map((l) => l.trim()).filter(Boolean);
  const looksLikeJsonl =
    lines.length > 1 && lines.every((l) => l[0] === '{') && trimmed[0] !== '[';

  if (looksLikeJsonl) {
    events = lines.map((line, i) => {
      try {
        return JSON.parse(line);
      } catch (err) {
        throw new Error('JSONL parse error on line ' + (i + 1) + ': ' + err.message);
      }
    });
  } else if (trimmed[0] === '[') {
    events = JSON.parse(trimmed);
  } else if (trimmed[0] === '{') {
    const obj = JSON.parse(trimmed);
    if (Array.isArray(obj)) {
      events = obj;
    } else if (Array.isArray(obj.events)) {
      events = obj.events;
      claims = obj.claims || null;
      verifierPublicKey = obj.verifierPublicKey || obj.verifierPublicKeyPem || null;
    } else if (obj.type) {
      events = [obj]; // single event object
    } else {
      throw new Error('unrecognized JSON object: expected { events: [...] } or a JSON array');
    }
  } else {
    // Single-line JSONL fallback.
    events = lines.map((line) => JSON.parse(line));
  }
  if (!Array.isArray(events) || !events.length) throw new Error('no events found');
  return { events, claims, verifierPublicKey };
}

/** Heuristic: does this text look like a PEM / bare-base64 public key? */
function looksLikePublicKey(text) {
  const t = String(text).trim();
  if (/-----BEGIN [A-Z ]*PUBLIC KEY-----/.test(t)) return true;
  // Bare base64 SPKI for Ed25519 is short and base64-only on a single logical line.
  return /^[A-Za-z0-9+/=\s]+$/.test(t) && t.replace(/\s+/g, '').length < 200 && t[0] !== '{' && t[0] !== '[';
}

/**
 * Load a parsed bundle into state, then asynchronously verify the verdict
 * signature and re-render. `events` is required; claims/publicKey optional.
 */
function loadBundle(bundle, sourceLabel) {
  state.trace = bundle.events || [];
  state.claims = bundle.claims || null;
  // The bundle-supplied key is the NON-AUTHORITATIVE "case B" fallback only: it
  // can flag a "signed by an untrusted bundle key" state but can NEVER make a
  // verdict authoritative. Trust is decided solely by getTrustedVerifierKeys().
  state.verifierPublicKey = bundle.verifierPublicKey || null;
  // A standalone verdict.json (capstone-style) takes precedence over any
  // verifier_verdict event embedded in the trace.
  state.standaloneVerdict = bundle.verdict || null;
  state.source = sourceLabel;
  state.sigResult = null; // reset; verifySignatureAndRerender fills it in
  state.chainResult = null; // reset; verifySignatureAndRerender fills it in
  renderAll();
  setStatus('Loaded ' + state.trace.length + ' events from ' + sourceLabel + '.', 'ok');
  verifySignatureAndRerender();
}

/**
 * Verify the current trace's verdict signature with Web Crypto, then re-render
 * the verdict panel with the gate result. Idempotent and safe to call repeatedly.
 */
async function verifySignatureAndRerender() {
  const verdict = deriveVerdict(state.trace);
  if (!verdict) {
    state.sigResult = null;
    state.chainResult = null;
    renderVerifierVerdict();
    return;
  }
  // Show the pending state immediately, then resolve.
  state.sigResult = null;
  state.chainResult = null;
  renderVerifierVerdict();

  // (1) signature over the verdict object, and (2) trace-chain + root binding —
  // BOTH are required before a verdict is AUTHORITATIVE. Compute them in
  // parallel; a valid signature over a verdict whose traceRootHash does not
  // match the loaded trace (or whose chain is broken) is NOT authoritative.
  const [sigResult, chainResult] = await Promise.all([
    verifyVerdictSignature(verdict, state.verifierPublicKey),
    verifyTraceIntegrity(state.trace, verdict),
  ]);
  state.sigResult = sigResult;
  state.chainResult = chainResult;
  renderVerifierVerdict();
}

/**
 * Verify the loaded trace's hash chain and bind its root to the verdict.
 * Returns { chainOk, brokenIndex, recomputedRoot, verdictRoot, rootMatches }.
 * `recomputedRoot` is the root computed from the loaded events;
 * `rootMatches` compares it to `verdict.traceRootHash`. NEVER throws.
 */
async function verifyTraceIntegrity(events, verdict) {
  const verdictRoot = (verdict && verdict.traceRootHash) || null;
  let chain;
  try {
    chain = await verifyChainBrowser(events);
  } catch (err) {
    chain = { ok: false };
  }
  const recomputedRoot = computeTraceRootBrowser(events);
  const rootMatches =
    typeof verdictRoot === 'string' &&
    verdictRoot.length > 0 &&
    recomputedRoot === verdictRoot;
  return {
    chainOk: !!chain.ok,
    brokenIndex: chain.brokenIndex,
    recomputedRoot,
    verdictRoot,
    rootMatches,
  };
}

/*
 * Bundle-load size caps (mirrors the extension's MAX_BUNDLE_FILE_BYTES /
 * MAX_BUNDLE_TOTAL_BYTES in extension/src/extension.ts). The panel reads each
 * selected/dropped file fully into memory and then parses/renders it; an
 * incident-scale trace could otherwise freeze the tab. We refuse to READ a file
 * over the per-file cap, or once the running total would exceed the total cap —
 * the embedded-sample path (window.GLYPHSPEK_SAMPLE_BUNDLE) never goes through
 * here, so this only bounds user-supplied files.
 */
const MAX_BUNDLE_FILE_BYTES = 8 * 1024 * 1024;
const MAX_BUNDLE_TOTAL_BYTES = 32 * 1024 * 1024;

/** Human-readable byte size for the size-cap status messages. */
function formatBundleBytes(bytes) {
  if (bytes < 1024) return bytes + ' B';
  const mib = bytes / (1024 * 1024);
  if (mib >= 1) return mib.toFixed(1) + ' MiB';
  return (bytes / 1024).toFixed(1) + ' KiB';
}

/**
 * Handle one or more dropped/picked files as a single run bundle. A bundle is
 * any combination of:
 *   - a trace (.jsonl one-event-per-line, a JSON array of events, or a wrapper
 *     { events, claims, verifierPublicKey }),
 *   - a standalone verdict.json (VerifierVerdict { checks, overallVerdict,
 *     traceRootHash, signature }), and
 *   - a verifier public key (.pem SPKI or bare base64).
 * This matches the capstone output at demo-output/capstone/ (trace.jsonl +
 * verdict.json + verifier-public-key.pem). The public key is resolved
 * out-of-band — it is NOT trusted from inside the trace/actor.
 */
function handleFiles(fileList) {
  const all = Array.prototype.slice.call(fileList || []);
  if (!all.length) return;

  // Size gate BEFORE any read: drop files over the per-file cap, and stop once
  // the running total would exceed the total cap. Bundles are small, so a large
  // file is almost certainly a mistake; we refuse to read it rather than freeze
  // the tab. Friendly, non-fatal status via the existing setStatus mechanism.
  const files = [];
  let runningTotal = 0;
  const skipped = [];
  for (const file of all) {
    const size = typeof file.size === 'number' ? file.size : 0;
    if (size > MAX_BUNDLE_FILE_BYTES) {
      skipped.push(
        'File ' + file.name + ' is too large (' + formatBundleBytes(size) +
          ') — bundles are small; max ' + formatBundleBytes(MAX_BUNDLE_FILE_BYTES) + ' per file',
      );
      continue;
    }
    if (runningTotal + size > MAX_BUNDLE_TOTAL_BYTES) {
      skipped.push(
        'File ' + file.name + ' skipped — bundle exceeds the ' +
          formatBundleBytes(MAX_BUNDLE_TOTAL_BYTES) + ' total limit',
      );
      continue;
    }
    runningTotal += size;
    files.push(file);
  }
  if (!files.length) {
    setStatus(
      skipped.length ? skipped.join('. ') + '.' : 'No readable files selected.',
      'err',
    );
    return;
  }

  let pending = files.length;
  let events = null;
  let claims = null;
  let verifierPublicKey = null;
  let verdict = null;
  const names = [];
  // Seed with any over-cap skips so they surface in the final status even when
  // the remaining (in-cap) files don't yield a trace/verdict.
  const errors = skipped.slice();

  function done() {
    if (pending > 0) return;
    if (!events && !verdict) {
      setStatus(
        'No trace or verdict found in ' +
          (names.join(', ') || 'the selected files') +
          (errors.length ? '. ' + errors.join('; ') : '. Provide a trace .json/.jsonl or verdict.json.'),
        'err',
      );
      return;
    }
    loadBundle({ events: events || [], claims, verifierPublicKey, verdict }, names.join(' + '));
    // If we loaded successfully but dropped some over-cap files, append a notice
    // (loadBundle just set the "Loaded …" status; keep that, add the skip note).
    if (skipped.length) setStatus('Loaded ' + state.trace.length + ' events. ' + skipped.join('. ') + '.', 'ok');
  }

  files.forEach((file) => {
    const reader = new FileReader();
    reader.onload = function () {
      const text = String(reader.result);
      const isPem = /\.pem$/i.test(file.name) || /-----BEGIN [A-Z ]*PUBLIC KEY-----/.test(text);
      try {
        if (isPem) {
          verifierPublicKey = text;
        } else if (/\.(json|jsonl|txt)$/i.test(file.name) || text.trim()[0] === '[' || text.trim()[0] === '{') {
          // Could be a verdict.json, a trace, or a wrapper. Try verdict first.
          const t = text.trim();
          let parsedAsVerdict = null;
          if (t[0] === '{') {
            try {
              const obj = JSON.parse(t);
              if (isVerdictObject(obj)) parsedAsVerdict = obj;
            } catch (_) {
              // not a single JSON object (e.g. JSONL) — fall through to trace parse
            }
          }
          if (parsedAsVerdict) {
            verdict = parsedAsVerdict;
          } else {
            const parsed = parseTraceText(text);
            events = parsed.events;
            if (parsed.claims) claims = parsed.claims;
            if (parsed.verifierPublicKey) verifierPublicKey = parsed.verifierPublicKey;
          }
        } else if (looksLikePublicKey(text)) {
          verifierPublicKey = text;
        } else {
          // Last resort: try to parse as a trace anyway.
          const parsed = parseTraceText(text);
          events = parsed.events;
          if (parsed.claims) claims = parsed.claims;
          if (parsed.verifierPublicKey) verifierPublicKey = parsed.verifierPublicKey;
        }
        names.push(file.name);
      } catch (err) {
        errors.push('"' + file.name + '": ' + err.message);
      }
      pending -= 1;
      done();
    };
    reader.onerror = function () {
      errors.push('could not read "' + file.name + '"');
      pending -= 1;
      done();
    };
    reader.readAsText(file);
  });
}

function exportTrace() {
  // Export the full run bundle, including the out-of-band verifier public key
  // so a downstream panel can re-verify the signature.
  const bundle = {
    runId: deriveRunHeader(state.trace).runId,
    events: state.trace,
    claims: state.claims,
    verifierPublicKey: state.verifierPublicKey || undefined,
  };
  const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = el('a');
  a.href = url;
  a.download = 'glyphspek-bundle-' + (deriveRunHeader(state.trace).runId || 'run').slice(0, 8) + '.json';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function loadSample() {
  if (REAL_SAMPLE_BUNDLE) {
    loadBundle(
      {
        events: REAL_SAMPLE_BUNDLE.events,
        claims: REAL_SAMPLE_BUNDLE.claims || null,
        verifierPublicKey: REAL_SAMPLE_BUNDLE.verifierPublicKey || null,
        // The default sample's verdict is DETACHED (real verdict.json), so it binds
        // to the trace's last-event root — keep it standalone so the bundle stays
        // chain+root+signature consistent (AUTHORITATIVE).
        verdict: REAL_SAMPLE_BUNDLE.verdict || null,
      },
      'embedded signed sample',
    );
  } else {
    loadBundle(
      { events: SAMPLE_TRACE, claims: SAMPLE_ACTOR_CLAIMS, verifierPublicKey: null },
      'embedded mock sample (no signature)',
    );
  }
}

/**
 * Demo: flip one byte of the signed verdict so the signature NO LONGER matches,
 * proving the gate. Deep-clones the real sample, mutates overallVerdict
 * (pass<->fail), and reloads — verification will fail and the badge flips to
 * "NOT verified".
 */
function tamperSample() {
  if (!REAL_SAMPLE_BUNDLE) {
    setStatus('Tamper demo needs the embedded signed sample (sample-bundle.js).', 'err');
    return;
  }
  const events = JSON.parse(JSON.stringify(REAL_SAMPLE_BUNDLE.events));
  // Tamper the SIGNED content (not the signature): the verdict the actor would
  // love to forge. The signature was computed over the original, so it breaks.
  // The default sample carries a DETACHED verdict; older mock-style samples carry
  // an in-trace verifier_verdict event. Tamper whichever is present.
  let verdict = REAL_SAMPLE_BUNDLE.verdict
    ? JSON.parse(JSON.stringify(REAL_SAMPLE_BUNDLE.verdict))
    : null;
  if (verdict) {
    verdict.overallVerdict = verdict.overallVerdict === 'pass' ? 'fail' : 'pass';
  } else {
    const verdictEvt = events.find((e) => e.type === 'verifier_verdict');
    if (verdictEvt && verdictEvt.payload) {
      verdictEvt.payload.overallVerdict =
        verdictEvt.payload.overallVerdict === 'pass' ? 'fail' : 'pass';
    }
  }
  loadBundle(
    {
      events,
      claims: REAL_SAMPLE_BUNDLE.claims || null,
      verifierPublicKey: REAL_SAMPLE_BUNDLE.verifierPublicKey || null,
      verdict,
    },
    'TAMPERED sample (one byte flipped — should NOT verify)',
  );
}

function setStatus(msg, kind) {
  const node = document.getElementById('load-status');
  if (!node) return;
  node.textContent = msg;
  node.className = 'load-status ' + (kind || '');
}

/* ================================================================== *
 * VS Code / Code-OSS WEBVIEW HOST BRIDGE.
 *
 * This file is the same trust surface used by the standalone prototype, hosted
 * verbatim inside a webview by the GlyphSpek extension. Browsers block file://
 * fetch and a webview's CSP forbids the native file picker reaching disk, so
 * the EXTENSION HOST reads a run-bundle directory (trace.jsonl + verdict.json +
 * verifier-public-key.pem [+ actor-claims.json]) with node:fs and posts the
 * RAW file contents here. The webview then parses, renders, and VERIFIES the
 * Ed25519 signature in-browser exactly as the prototype does — the host never
 * tells the webview whether a verdict is trustworthy; the gate stays in the
 * webview where Web Crypto runs. When not hosted in a webview (acquireVsCodeApi
 * absent) this is a no-op and the page behaves like the plain prototype.
 * ================================================================== */

const vscodeApi =
  typeof acquireVsCodeApi === 'function' ? acquireVsCodeApi() : null;

/**
 * Normalize the capstone-style actor-claims.json shape
 * ({ plan, summary, claimedFilesChanged, claimedChecks:[{name, claimedStatus}] })
 * to the shape the Actor-claims renderer expects
 * ({ plan, summary, claimedChangedFiles, claimedChecks:[{name, claim}] }).
 * Already-normalized claims pass through unchanged. Claims are NEVER merged
 * with a verdict — they remain the actor's non-authoritative self-report.
 */
function normalizeClaims(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const out = {
    plan: raw.plan,
    summary: raw.summary,
    claimedChangedFiles: raw.claimedChangedFiles || raw.claimedFilesChanged || null,
  };
  const checks = raw.claimedChecks;
  if (Array.isArray(checks)) {
    out.claimedChecks = checks.map((c) => ({
      name: c && c.name,
      claim: c && (c.claim != null ? c.claim : c.claimedStatus),
    }));
  }
  return out;
}

/**
 * Ingest run-bundle files posted by the extension host. Each entry is
 * { name, text } (the raw on-disk contents). Reuses the exact same parsing /
 * classification logic as the drag-drop path so behavior is identical, then
 * loads the assembled bundle through loadBundle (which triggers in-browser
 * signature verification). The verifier public key is taken ONLY from a .pem /
 * PUBLIC KEY file (out-of-band), never trusted from inside the trace.
 */
function ingestPostedFiles(files) {
  const list = Array.isArray(files) ? files : [];
  if (!list.length) {
    setStatus('No files in the selected run bundle.', 'err');
    return;
  }

  let events = null;
  let claims = null;
  let verifierPublicKey = null;
  let verdict = null;
  const names = [];
  const errors = [];

  for (const file of list) {
    const name = (file && file.name) || 'file';
    const text = file && typeof file.text === 'string' ? file.text : '';
    const isPem = /\.pem$/i.test(name) || /-----BEGIN [A-Z ]*PUBLIC KEY-----/.test(text);
    try {
      if (isPem) {
        verifierPublicKey = text;
      } else if (/actor-claims\.json$/i.test(name)) {
        // Standalone capstone-style actor claims file.
        const parsed = normalizeClaims(JSON.parse(text.trim()));
        if (parsed) claims = parsed;
      } else if (/\.(json|jsonl|txt)$/i.test(name) || text.trim()[0] === '[' || text.trim()[0] === '{') {
        const t = text.trim();
        let parsedAsVerdict = null;
        if (t[0] === '{') {
          try {
            const obj = JSON.parse(t);
            if (isVerdictObject(obj)) parsedAsVerdict = obj;
          } catch (_) {
            // not a single JSON object (e.g. JSONL) — fall through to trace parse
          }
        }
        if (parsedAsVerdict) {
          verdict = parsedAsVerdict;
        } else {
          const parsed = parseTraceText(text);
          events = parsed.events;
          if (parsed.claims) claims = parsed.claims;
          if (parsed.verifierPublicKey) verifierPublicKey = parsed.verifierPublicKey;
        }
      } else if (looksLikePublicKey(text)) {
        verifierPublicKey = text;
      } else {
        const parsed = parseTraceText(text);
        events = parsed.events;
        if (parsed.claims) claims = parsed.claims;
        if (parsed.verifierPublicKey) verifierPublicKey = parsed.verifierPublicKey;
      }
      names.push(name);
    } catch (err) {
      errors.push('"' + name + '": ' + (err && err.message ? err.message : String(err)));
    }
  }

  if (!events && !verdict) {
    setStatus(
      'No trace or verdict found in ' +
        (names.join(', ') || 'the selected run bundle') +
        (errors.length ? '. ' + errors.join('; ') : '. Provide a trace .json/.jsonl or verdict.json.'),
      'err',
    );
    return;
  }
  loadBundle({ events: events || [], claims, verifierPublicKey, verdict }, names.join(' + '));
}

/**
 * The trusted-run KIND the host last asked us to offer (sweep-20 High #3), if any.
 * Posting `startTrustedRun` with this kind is the first-party operator gesture that
 * the host turns into a product-trusted run. A third-party extension cannot reach
 * this state because it cannot post into our webview.
 */
let pendingTrustedRunKind = null;

/** Show/hide the first-party "Start run" affordance for a given run kind. */
function showTrustedRunOffer(kind) {
  pendingTrustedRunKind = kind || null;
  const offer = document.getElementById('trusted-run-offer');
  if (offer) offer.hidden = !pendingTrustedRunKind;
}

/** Wire the host→webview message channel. Idempotent / safe if no host. */
function wireHostBridge() {
  window.addEventListener('message', function (event) {
    const msg = event && event.data;
    if (!msg || typeof msg !== 'object') return;
    if (msg.type === 'loadBundleFiles') {
      ingestPostedFiles(msg.files);
    } else if (msg.type === 'offerTrustedRun') {
      // A GlyphSpek command asked to start a trusted run. Surface the first-party
      // "Start run" button; the operator clicking it is the gesture that the host
      // (and ONLY a webview message) turns into a product-trusted run.
      showTrustedRunOffer(msg.kind);
    }
  });
  // Tell the host the panel is ready (so a load requested before the webview
  // finished booting can be replayed).
  if (vscodeApi) {
    try {
      vscodeApi.postMessage({ type: 'ready' });
    } catch (_) {
      /* no-op */
    }
  }
}

/* ------------------------------------------------------------------ *
 * Wiring.
 * ------------------------------------------------------------------ */

function renderAll() {
  renderRunHeader();
  renderTimeline();
  renderClaimsVsVerdict();
  renderDerivedSections();
}

function wireControls() {
  const picker = document.getElementById('file-input');
  if (picker) {
    picker.addEventListener('change', function (e) {
      if (e.target.files && e.target.files.length) handleFiles(e.target.files);
    });
  }

  // In the webview, the native file picker cannot reach disk; route "Load run
  // bundle…" through the extension host, which reads the directory with node:fs
  // and posts the file contents back for in-webview parsing + verification.
  const loadBtn = document.getElementById('load-host-btn');
  if (loadBtn) {
    loadBtn.addEventListener('click', function () {
      if (vscodeApi) {
        vscodeApi.postMessage({ type: 'requestLoadBundle' });
      }
    });
  }

  // FIRST-PARTY TRUSTED-RUN GESTURE (sweep-20 High #3). Clicking "Start run" posts
  // `startTrustedRun` to the host — the ONLY path that mints an operator gesture and
  // creates a product-trusted run. We clear the offer after posting (single click).
  const startRunBtn = document.getElementById('trusted-run-start-btn');
  if (startRunBtn) {
    startRunBtn.addEventListener('click', function () {
      if (vscodeApi && pendingTrustedRunKind) {
        vscodeApi.postMessage({ type: 'startTrustedRun', kind: pendingTrustedRunKind });
      }
      showTrustedRunOffer(null);
    });
  }

  const exportBtn = document.getElementById('export-btn');
  if (exportBtn) exportBtn.addEventListener('click', exportTrace);

  const sampleBtn = document.getElementById('sample-btn');
  if (sampleBtn) sampleBtn.addEventListener('click', loadSample);

  const tamperBtn = document.getElementById('tamper-btn');
  if (tamperBtn) tamperBtn.addEventListener('click', tamperSample);

  // Drag-and-drop onto the whole document.
  const dz = document.body;
  ['dragenter', 'dragover'].forEach((evtName) => {
    dz.addEventListener(evtName, function (e) {
      e.preventDefault();
      document.body.classList.add('dragging');
    });
  });
  ['dragleave', 'drop'].forEach((evtName) => {
    dz.addEventListener(evtName, function (e) {
      e.preventDefault();
      if (evtName === 'drop') {
        const files = e.dataTransfer && e.dataTransfer.files;
        if (files && files.length) handleFiles(files);
      }
      document.body.classList.remove('dragging');
    });
  });
}

document.addEventListener('DOMContentLoaded', function () {
  wireControls();
  wireHostBridge();
  renderAll();
  // Verify the default (signed) sample's signature in-browser on open and
  // re-render the verdict gate with the result.
  verifySignatureAndRerender();
});
